package MatriceService;


/**
* MatriceService/_calculeMatricielStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from matrice.idl
* Sunday, January 17, 2021 3:31:15 PM PST
*/

public class _calculeMatricielStub extends org.omg.CORBA.portable.ObjectImpl implements MatriceService.calculeMatriciel
{

  public int[][] addition (int[][] m1, int[][] m2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addition", true);
                MatriceService.MatriceHelper.write ($out, m1);
                MatriceService.MatriceHelper.write ($out, m2);
                $in = _invoke ($out);
                int $result[][] = MatriceService.MatriceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addition (m1, m2        );
            } finally {
                _releaseReply ($in);
            }
  } // addition

  public int[][] multiplication (int[][] m1, int[][] m2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("multiplication", true);
                MatriceService.MatriceHelper.write ($out, m1);
                MatriceService.MatriceHelper.write ($out, m2);
                $in = _invoke ($out);
                int $result[][] = MatriceService.MatriceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return multiplication (m1, m2        );
            } finally {
                _releaseReply ($in);
            }
  } // multiplication

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MatriceService/calculeMatriciel:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _calculeMatricielStub
