package MatriceService;


/**
* MatriceService/calculeMatricielHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from matrice.idl
* Sunday, January 17, 2021 3:31:15 PM PST
*/

abstract public class calculeMatricielHelper
{
  private static String  _id = "IDL:MatriceService/calculeMatriciel:1.0";

  public static void insert (org.omg.CORBA.Any a, MatriceService.calculeMatriciel that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MatriceService.calculeMatriciel extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MatriceService.calculeMatricielHelper.id (), "calculeMatriciel");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MatriceService.calculeMatriciel read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_calculeMatricielStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MatriceService.calculeMatriciel value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MatriceService.calculeMatriciel narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MatriceService.calculeMatriciel)
      return (MatriceService.calculeMatriciel)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MatriceService._calculeMatricielStub stub = new MatriceService._calculeMatricielStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MatriceService.calculeMatriciel unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MatriceService.calculeMatriciel)
      return (MatriceService.calculeMatriciel)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MatriceService._calculeMatricielStub stub = new MatriceService._calculeMatricielStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
