package MatriceService;

/**
 * MatriceService/calculeMatricielPOA.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from matrice.idl Sunday, January 17, 2021
 * 3:31:15 PM PST
 */
public abstract class calculeMatricielPOA extends org.omg.PortableServer.Servant
        implements MatriceService.calculeMatricielOperations, org.omg.CORBA.portable.InvokeHandler {

    // Constructors
    private static java.util.Hashtable _methods = new java.util.Hashtable();

    static {
        _methods.put("addition", new java.lang.Integer(0));
        _methods.put("multiplication", new java.lang.Integer(1));
    }

    public org.omg.CORBA.portable.OutputStream _invoke(String $method,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler $rh) {
        org.omg.CORBA.portable.OutputStream out = null;
        java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
        if (__method == null) {
            throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        switch (__method.intValue()) {
            case 0: // MatriceService/calculeMatriciel/addition
            {
                int m1[][] = MatriceService.MatriceHelper.read(in);
                int m2[][] = MatriceService.MatriceHelper.read(in);
                int $result[][] = null;
                $result = this.addition(m1, m2);
                out = $rh.createReply();
                MatriceService.MatriceHelper.write(out, $result);
                break;
            }

            case 1: // MatriceService/calculeMatriciel/multiplication
            {
                int m1[][] = MatriceService.MatriceHelper.read(in);
                int m2[][] = MatriceService.MatriceHelper.read(in);
                int $result[][] = null;
                $result = this.multiplication(m1, m2);
                out = $rh.createReply();
                MatriceService.MatriceHelper.write(out, $result);
                break;
            }

            default:
                throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
        }

        return out;
    } // _invoke

    // Type-specific CORBA::Object operations
    private static String[] __ids = {
        "IDL:MatriceService/calculeMatriciel:1.0"};

    public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
        return (String[]) __ids.clone();
    }

    public calculeMatriciel _this() {
        return calculeMatricielHelper.narrow(
                super._this_object());
    }

    public calculeMatriciel _this(org.omg.CORBA.ORB orb) {
        return calculeMatricielHelper.narrow(
                super._this_object(orb));
    }

} // class calculeMatricielPOA
