package MatriceService;


/**
* MatriceService/calculeMatriciel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from matrice.idl
* Sunday, January 17, 2021 3:31:15 PM PST
*/

public interface calculeMatriciel extends calculeMatricielOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calculeMatriciel
