package MatriceService;

/**
* MatriceService/calculeMatricielHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from matrice.idl
* Sunday, January 17, 2021 3:31:15 PM PST
*/

public final class calculeMatricielHolder implements org.omg.CORBA.portable.Streamable
{
  public MatriceService.calculeMatriciel value = null;

  public calculeMatricielHolder ()
  {
  }

  public calculeMatricielHolder (MatriceService.calculeMatriciel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatriceService.calculeMatricielHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatriceService.calculeMatricielHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatriceService.calculeMatricielHelper.type ();
  }

}
