package MatriceService;


/**
* MatriceService/calculeMatricielOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from matrice.idl
* Sunday, January 17, 2021 3:31:15 PM PST
*/

public interface calculeMatricielOperations 
{
  int[][] addition (int[][] m1, int[][] m2);
  int[][] multiplication (int[][] m1, int[][] m2);
} // interface calculeMatricielOperations
