package MatriceService;


/**
* MatriceService/colonneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from matrice.idl
* Sunday, January 17, 2021 3:31:15 PM PST
*/

public final class colonneHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public colonneHolder ()
  {
  }

  public colonneHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatriceService.colonneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatriceService.colonneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatriceService.colonneHelper.type ();
  }

}
