package MatriceService;


/**
* MatriceService/MatriceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from matrice.idl
* Sunday, January 17, 2021 3:31:15 PM PST
*/

public final class MatriceHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[][] = null;

  public MatriceHolder ()
  {
  }

  public MatriceHolder (int[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatriceService.MatriceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatriceService.MatriceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatriceService.MatriceHelper.type ();
  }

}
